### ISSUE TITLE
Another release

### ISSUE THREAD

**Issue by fivaldi** [libersoft/pysmime#10]
@lgaggini Please for another release (0.2.1?) with the most recent changes in the master branch. Or, if you added me to the project, I would do it.

This should be OK for some time.

Thanks very much!

**Comment by lgaggini** [comment]
I put on pypi the 0.2.1 release. You are doing a great work on this project so I also add you as collaborator to the project here on github and on pypi too (I add to the project the user fivaldi, let me know if i'm wrong).

**Comment by fivaldi** [comment]
@lgaggini Thank you again, "fivaldi" is the right one. I like the way we cooperate! :-)
