### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by fivaldi** [libersoft/pysmime#4]
Hi all.

I would like to request a new PyPI release, if possible. The current master as of aff374dad2b8f47087550285350a19110a7939ba seems to be stable/working (tested on Fedora).

Thank you,
Filip

**Comment by fivaldi** [comment]
Or even better after #5 is merged.

**Comment by lgaggini** [comment]
Too bad I lost my PyPI credentials, I opened a [support request](https://sourceforge.net/p/pypi/support-requests/720/) about 1 year ago wihtout answer. Maybe I'll open a new account soon.

**Comment by fivaldi** [comment]
@lgaggini No problem. I will use the git reference in the meanwhile for one project where I need pysmime library.

I just need to request merge for #6 now.

Please, let me know when you are successful with the PyPI. I would then switch my `requirements.txt` from the git ref simply to `pysmime`.

Thanks again very much!

**Comment by fivaldi** [comment]
#7 is another new candidate.

**Comment by lgaggini** [comment]
Merged, next week I'll open also a new account on pypi and I'll upload the new version.

**Comment by lgaggini** [comment]
I open a new account on pypy and I upload the last pysmime versione as pysmime3, at: 

https://pypi.org/project/pysmime3/

:)
